name: Build

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@main
      - name: Build Deb
        run: |
          brew install ldid xz
          export THEOS=~/theos
          git clone --recursive https://github.com/theos/theos $THEOS
          make clean package XCODE=/Applications/Xcode_14.0.1.app FINALPACKAGE=1

      - uses: actions/upload-artifact@main
        with:
          name: package
          path: packages/*.deb

  upload:
    needs: build
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@main
      - name: Download Artifact
        uses: actions/download-artifact@main

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Draft Release
          body: ''
          draft: true

      - name: Attach Deb To Release
        run: |
          set -x
          gh release upload ${GITHUB_REF##*/} packages/*.deb
