name: Build

on:
  - push
  - workflow_dispatch

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Draft Release
          body: ''
          draft: true

  build:
    needs: create_release
    runs-on: macos-12
    steps:
      - uses: actions/checkout@main
      - name: Build Deb
        uses: L1ghtmann/theos-build@main
        with:
          extra_args: "XCODE=/Applications/Xcode_14.0.1.app FINALPACKAGE=1"

      - name: Attach Deb To Release
        run: |
          set -x
          gh release upload ${GITHUB_REF##*/} packages/*.deb
