name: Build

on:
  push:
    branches: [ pr ]
  pull_request:
    branches: [ pr ]

jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@main
      - name: Build latest ldid
        run: |
          # Install ldid then override so theos-build doesn't return non-zero for install
          brew install openssl ldid
          export PKG_CONFIG_PATH="/usr/local/opt/openssl@3/lib/pkgconfig"
          sudo rm /usr/local/bin/ldid
          git clone https://github.com/ProcursusTeam/ldid/
          cd ldid
          make -j$(sysctl -n hw.ncpu) install
          cd

      - name: theos-build
        uses: L1ghtmann/theos-build@main

      - uses: actions/upload-artifact@main
        with:
          name: package
          path: packages/*.deb

  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Download artifacts
        uses: actions/download-artifact@main

      - name: Create release
        id: create_release
        uses: actions/create-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 0.0.1
          release_name: Trial 1
          draft: false
          prerelease: false

      - name: Attach debs to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          debs=()
          for deb in **/*.deb; do
            debs+=("-a" "$deb")
          done
          hub release edit "${debs[@]}" -m "Trial 1" "0.0.1"
