name: Build

on:
  push:
    branches: [ pr ]
  pull_request:
    branches: [ pr ]

jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@main
      - name: theos-build
        uses: L1ghtmann/theos-build@main

      - uses: actions/upload-artifact@main
        with:
          name: package
          path: packages/*.deb

  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Download artifacts
        uses: actions/download-artifact@main

      - name: Create release
        id: create_release
        uses: actions/create-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 0.0.2
          release_name: Trial 2
          draft: false
          prerelease: false

      - name: Attach debs to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          debs=()
          for deb in **/*.deb; do
            debs+=("-a" "$deb")
          done
          hub release edit "${debs[@]}" -m "Trial 2" "0.0.2"
